# Generated by Django 3.2.13 on 2023-09-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to='screen_recordings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
